config/routes.rb
Rails.application.routes.draw do
  
  
  devise_for :admins 
    
  devise_scope :admin do  
    get '/admins/sign_out' => 'devise/sessions#destroy'     
 end
  resources :categories
  get 'orderitems/index'
  get 'orderitems/show'
  get 'orderitems/new'
  get 'orderitems/edit'
  resources :orders do
    resources:orderitems
  end
  devise_for :views
  devise_for :users do
    resources :orders 
  end
  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
 end

  
  get '/checkout' => 'cart#createOrder'

  root 'static_pages#home'
  
  get '/home' => 'static_pages#home'
  get '/help' => 'static_pages#help'
  get '/about' => 'static_pages#about'
  get '/category' => 'static_pages#categories'
 
  get '/login' => 'user#login' 
  get '/logout' => 'user#logout'
  
  get 'category/:title' => 'static_pages#category'
  resources :items
  
  get '/cart' => 'cart#index'
  get '/cart/clear' => 'cart#clear'
  get '/cart/:id' => 'cart#add'
  get '/cart/remove/:id' => 'cart#remove'
  get '/cart/reduce/:id' => 'cart#reduce'
  get '/cart/increase/:id' => 'cart#increase'
  
  
  get '/search' => 'items#search'
  
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  def order_params
    params.require(:order).permit( :order_date, :user_id, :status)
    end
   
   
   has_many :orderitems, :dependent => :destroy
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  def index
    @user = User.find(current_user.id)
    @orders = Order.all
    @orderitems = Orderitem.all
  end

  # GET /orders/1
  def show
    @user = User.find(current_user.id)
    @orderitems = Orderitem.all
    
    #@orderitems = Orderitem.where(order_id: params[:id])
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  def create
    @order = Order.new(order_params)

    if @order.save
      redirect_to @order, notice: 'Order was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /orders/1
  def update
    if @order.update(order_params)
      redirect_to @order, notice: 'Order was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /orders/1
  def destroy
    @order.destroy
    redirect_to orders_url, notice: 'Order was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def order_params
      params.require(:order).permit(:order_date, :user_id, :status)
    end
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/views/orders/_form.html.erb
<%= form_with(model: order, local: true) do |form| %>
  <% if order.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(order.errors.count, "error") %> prohibited this order from being saved:</h2>

      <ul>
        <% order.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :order_date %>
    <%= form.datetime_select :order_date %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :status %>
    <%= form.text_field :status %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/orders/edit.html.erb
<h1>Editing Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Show', @order %> |
<%= link_to 'Back', orders_path %>

app/views/orders/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Your Orders</h1>

  <table>
    <thead>
      <tr>
        <th>Order date</th>
        <th>User</th>
        <th>Status</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
        
      <% @orders.each do |order| %>
        <%@order=order%>
        <% if @order.user.email == @user.email %>
          <tr>
            <td><%= order.order_date %></td>
            <td><%= order.user_id %></td>
            <td><%= order.status %></td>
            <td><%= link_to 'Show', order %></td>
            <td><%= link_to 'Edit', edit_order_path(order) %></td>
            <td><%= link_to 'Destroy', order, method: :delete, data: { confirm: 'Are you sure?' } %></td>
          </tr>
        <% end %>
        
      <% end %>
    </tbody>
  </table>

  <br>
<% if false %>

  <h2>Order Items</h2>
  <table id="customers">
    <% @orderitems.each do |orderitem| %>
        <tr>
          <td><%= orderitem.created_at %></td>
          
          <td><%= orderitem.title %></td>
        <td><%= orderitem.order_id %></td>
        
        </tr>
      <% end %>
  
    <tr></tr>
    </table>
        
    </div>

<%end%>
   
<%= link_to 'New Order', new_order_path %>

app/views/orders/new.html.erb
<h1>New Order</h1>

<%= render 'form', order: @order %>

<%= link_to 'Back', orders_path %>

app/views/orders/show.html.erb
<p id="notice"><%= notice %></p>
<% if @order.user.email == @user.email %>
  <p>
    <strong>Order date:</strong>
    <%= @order.order_date %>
    
  </p>

  <p>
    <strong>User:</strong>
    <%= @order.user_id %>
  </p>

  <p>
    <strong>Status:</strong>
    <%= @order.status %>
  </p>
  <%= link_to 'Edit', edit_order_path(@order) %>
<% else %>
  <h1>You did not place this order</h1>
<% end %>

   |
  <%= link_to 'Back', orders_path %>