config/routes.rb
Rails.application.routes.draw do
  
  
  devise_for :admins 
    
  devise_scope :admin do  
    get '/admins/sign_out' => 'devise/sessions#destroy'     
 end
  resources :categories
  get 'orderitems/index'
  get 'orderitems/show'
  get 'orderitems/new'
  get 'orderitems/edit'
  resources :orders do
    resources:orderitems
  end
  devise_for :views
  devise_for :users do
    resources :orders 
  end
  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
 end

  
  get '/checkout' => 'cart#createOrder'

  root 'static_pages#home'
  
  get '/home' => 'static_pages#home'
  get '/help' => 'static_pages#help'
  get '/about' => 'static_pages#about'
  get '/category' => 'static_pages#categories'
 
  get '/login' => 'user#login' 
  get '/logout' => 'user#logout'
  
  get 'category/:title' => 'static_pages#category'
  resources :items
  
  get '/cart' => 'cart#index'
  get '/cart/clear' => 'cart#clear'
  get '/cart/:id' => 'cart#add'
  get '/cart/remove/:id' => 'cart#remove'
  get '/cart/reduce/:id' => 'cart#reduce'
  get '/cart/increase/:id' => 'cart#increase'
  
  
  get '/search' => 'items#search'
  
end

app/models/item.rb
class Item < ApplicationRecord
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  def index
    @items = Item.all
  end

  # GET /items/1
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  def create
    @item = Item.new(item_params)

    if @item.save
      redirect_to @item, notice: 'Item was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /items/1
  def update
    if @item.update(item_params)
      redirect_to @item, notice: 'Item was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /items/1
  def destroy
    @item.destroy
    redirect_to items_url, notice: 'Item was successfully destroyed.'
  end


  # GET /search
  def search
    @items = Item.where("title LIKE ?","%" + params[:q] + "%")
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def item_params
      params.require(:item).permit(:title, :description, :price, :image_url, :country, :brand)
    end
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/views/items/_form.html.erb
<div class="mainCont">
<%= form_with(model: item, local: true) do |form| %>
 <% if item.errors.any? %>
 <div id="error_explanation">
 <h2><%= pluralize(item.errors.count, "error") %> prohibited this item from being saved:</h2>
 <ul>
 <% item.errors.full_messages.each do |message| %>
 <li><%= message %></li>
 <% end %>
 </ul>
 </div>
 <% end %>
 <div class="field">
 <%= form.label :title %>
 <%= form.text_field :title, id: :item_titl, :type =>"text"%>
 </div>
 <div class="field">
 <%= form.label :description %>
 <%= form.text_field :description, id: :item_description, :type =>"text" %>
 </div>
 <div class="field">
 <%= form.label :price %>
 <%= form.text_field :price, id: :item_price, :type =>"text" %>
 </div>
 <div class="field">
 <%= form.label :image_url %>
 <%= form.text_field :image_url, id: :item_image_url %>
 </div>
 <div class="field">
 <%= form.label :contry %>
 <%= form.text_field :country, id: :item_country, :type =>"text" %>
 </div>
 <div class="field">
 <%= form.label :brand %>
 <%= form.text_field :brand, id: :item_brand, :type =>"text" %>
 </div>
 <div class="actions">
 <%= form.submit %>
 </div>
<% end %>
</div>

app/views/items/_search.html.erb
<h2>You Searched Our Product Catalog For <%= @search_term %></h2>

<% if @items.length == 0  %>
<br />
<h2>No products were found to match your search</h2>
<% end %>


<table class="catalog">
  <% @items.each do |item| %>
      <tr>
        <td>
          <div class="image">
            <%= link_to (image_tag item.image_url, :style => "height:100px"), item %>
          </div>
          <div class="title">
            <%= link_to item.title, item %>
          </div>
          <div class="description">
            <%= item.description %>
          </div>  
          <div class="price">
             <%= number_to_currency(item.price, :unit => "€") %>
          </div>
          <div class="links">
            <% if user_signed_in? %>
              <%= link_to 'Edit', edit_item_path(item) %>
              <%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %>
            <%else%>
            
              <a href="/cart/<%= item.id %>">Add to Cart</a>
            <%end%>  
        </div>
        </td>
      </tr>
    <% end %>
</table>

app/views/items/edit.html.erb
<h1>Editing Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Show', @item %> |
<%= link_to 'Back', items_path %>

app/views/items/index.html.erb
<p id="notice"><%= notice %></p>

 <div id="itemsContainer">
  
  <h1>Items</h1>
     
      <% @items.each do |item| %>
      <div class="itemhols">
       <h1><%= item.title %></h1>
      
      <%= link_to (image_tag item.image_url, :class => "itemholsIm"), item %>
      <p><%= item.description %></p>
      <p>Price <%= number_to_currency(item.price, :unit => "€") %>
      <br>
        Country: <%= item.country %>
      <br>
        Brand: <%= item.brand %></p>
      
      <p>
        
          <a href="/cart/<%= item.id %>" class="button">Add To Cart</a>
        
          <%= link_to 'Show',  item, :class => "button", :role => "button" %>
        
        <% if admin_signed_in? %>
          <%= link_to 'Edit', edit_item_path(item), :class =>"button", :role=>"button" %>
          <%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' }, :class =>"button", :role=>"button" %>
        <% end %>
       </p>
          
      </div>
    <% end %>
      
</div>

<br>

app/views/items/new.html.erb
<h1>New Item</h1>

<%= render 'form', item: @item %>

<%= link_to 'Back', items_path %>

app/views/items/search.html.erb
<h2>You Searched Our Product Catalog For <%= @search_term %></h2>

<% if @items.length == 0  %>
<br />
<h2>No products were found to match your search</h2>
<% end %>


<table class="catalog">
  <% @items.each do |item| %>
      <tr>
        <td>
          <div class="image">
            <%= link_to (image_tag item.image_url, :style => "height:100px"), item %>
          </div>
          <div class="title">
            <%= link_to item.title, item %>
          </div>
          <div class="description">
            <%= item.description %>
          </div>  
          <div class="price">
             <%= number_to_currency(item.price, :unit => "€") %>
          </div>
          <div class="links">
            <% if user_signed_in? %>
              <%= link_to 'Edit', edit_item_path(item) %>
              <%= link_to 'Destroy', item, method: :delete, data: { confirm: 'Are you sure?' } %>
            <%else%>
            
              <a href="/cart/<%= item.id %>">Add to Cart</a>
            <%end%>  
        </div>
        </td>
      </tr>
    <% end %>
</table>

app/views/items/show.html.erb
<p id="notice"><%= notice %></p>
<div id="itemsContainer">
 <h1><%= @item.title %></h1>
 <%= image_tag @item.image_url, :class => 'welcomIm' %>
 <h2><%= @item.description %></h2>

 <div class="itemhols">
 <p>Price <%= number_to_currency(@item.price, :unit => "€") %>
 <br>
 Country: <%= @item.country %>
 <br>
 Brand: <%= @item.brand %></p>

 <p>
 <a href="/cart/<%= @item.id %>" class="button">Add To Cart</a>
 <%= link_to 'Back', items_path, :class => "button", :role => "button" %>
    <% if session[:login] == 1 %>
        <%= link_to 'Edit', edit_item_path(@item), :class => "button", :role => "button" %>
    <% end %>
 </p>

 </div>


 </div>