config/routes.rb
Rails.application.routes.draw do
  
  
  devise_for :admins 
    
  devise_scope :admin do  
    get '/admins/sign_out' => 'devise/sessions#destroy'     
 end
  resources :categories
  get 'orderitems/index'
  get 'orderitems/show'
  get 'orderitems/new'
  get 'orderitems/edit'
  resources :orders do
    resources:orderitems
  end
  devise_for :views
  devise_for :users do
    resources :orders 
  end
  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
 end

  
  get '/checkout' => 'cart#createOrder'

  root 'static_pages#home'
  
  get '/home' => 'static_pages#home'
  get '/help' => 'static_pages#help'
  get '/about' => 'static_pages#about'
  get '/category' => 'static_pages#categories'
 
  get '/login' => 'user#login' 
  get '/logout' => 'user#logout'
  
  get 'category/:title' => 'static_pages#category'
  resources :items
  
  get '/cart' => 'cart#index'
  get '/cart/clear' => 'cart#clear'
  get '/cart/:id' => 'cart#add'
  get '/cart/remove/:id' => 'cart#remove'
  get '/cart/reduce/:id' => 'cart#reduce'
  get '/cart/increase/:id' => 'cart#increase'
  
  
  get '/search' => 'items#search'
  
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/category.rb
class Category < ApplicationRecord
end

app/models/item.rb
class Item < ApplicationRecord
end

app/models/order.rb
class Order < ApplicationRecord
  belongs_to :user
  def order_params
    params.require(:order).permit( :order_date, :user_id, :status)
    end
   
   
   has_many :orderitems, :dependent => :destroy
end

app/models/orderitem.rb
class Orderitem < ApplicationRecord
  belongs_to :order
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  def user_params
  params.require(:user).permit(:email, :password, :password_confirmation, :remember_me)
  end
  has_many :orders
end

app/models/view.rb
class View < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/controllers/cart_controller.rb
class CartController < ApplicationController
  before_action :authenticate_user!
   
  def add
        # get the id of the product
        id = params[:id]
        
        # if the cart exists use it, or if not make a new cart.
        
        if session[:cart] then
          cart = session[:cart]
        else
          session[:cart] = {}
          cart = session[:cart]
        end  
        
        # check if ite is there and if so increment the quantity by 1
        # if the item is not there then set the quantity to be 1
        
        if cart[id] then
          cart[id] = cart[id] + 1
        else
          cart[id] = 1
        end 
    
    redirect_to :action => :index
  end
  
  def clear
    #sets session variable to nil and bring back to index
    session[:cart] = nil
    redirect_to :action => :index
  end
    
  
  def remove
    id = params[:id]
    cart = session[:cart]
    cart.delete id
    redirect_to :action => :index
  end
  
  def reduce
    id = params[:id]
    cart = session[:cart]
   cart[id] = cart[id] - 1
    
    redirect_to :action => :index
  end
  
  
  def increase
    id = params[:id]
    cart = session[:cart]
    cart[id] = cart[id] + 1
    
    redirect_to :action => :index
  end
  
  
  def index
    # pass the cart to be displayed
    
    if session[:cart] then
      @cart = session[:cart]
    else
      @cart = {}
    end
    
  end
  
  def createOrder
    
      # @orderNo = Order.find(params[:id])
        
        
      
      @user = User.find(current_user.id)

      
      @order = @user.orders.build(:order_date => DateTime.now, :status => 'Pending')
      @order.save

      
      @cart = session[:cart] || {} # Get the content of the Cart
      @cart.each do | id, quantity |
      item = Item.find_by_id(id)
      @orderitem = @order.orderitems.build(:item_id => item.id, :title => item.title, :description => item.description, :quantity => quantity, :price=> item.price)
      @orderitem.save
      end
      
      @orders = Order.last
      @orderitems = Orderitem.where(order_id: Order.last)
      session[:cart] = nil
      # session[:cart] = nil # Hidden for development so I can refresh the page
      
  end
  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  before_action :set_item, only: [:show, :edit, :update, :destroy]

  # GET /items
  def index
    @items = Item.all
  end

  # GET /items/1
  def show
  end

  # GET /items/new
  def new
    @item = Item.new
  end

  # GET /items/1/edit
  def edit
  end

  # POST /items
  def create
    @item = Item.new(item_params)

    if @item.save
      redirect_to @item, notice: 'Item was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /items/1
  def update
    if @item.update(item_params)
      redirect_to @item, notice: 'Item was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /items/1
  def destroy
    @item.destroy
    redirect_to items_url, notice: 'Item was successfully destroyed.'
  end


  # GET /search
  def search
    @items = Item.where("title LIKE ?","%" + params[:q] + "%")
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_item
      @item = Item.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def item_params
      params.require(:item).permit(:title, :description, :price, :image_url, :country, :brand)
    end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController
  before_action :set_order, only: [:show, :edit, :update, :destroy]

  # GET /orders
  def index
    @user = User.find(current_user.id)
    @orders = Order.all
    @orderitems = Orderitem.all
  end

  # GET /orders/1
  def show
    @user = User.find(current_user.id)
    @orderitems = Orderitem.all
    
    #@orderitems = Orderitem.where(order_id: params[:id])
  end

  # GET /orders/new
  def new
    @order = Order.new
  end

  # GET /orders/1/edit
  def edit
  end

  # POST /orders
  def create
    @order = Order.new(order_params)

    if @order.save
      redirect_to @order, notice: 'Order was successfully created.'
    else
      render :new
    end
  end

  # PATCH/PUT /orders/1
  def update
    if @order.update(order_params)
      redirect_to @order, notice: 'Order was successfully updated.'
    else
      render :edit
    end
  end

  # DELETE /orders/1
  def destroy
    @order.destroy
    redirect_to orders_url, notice: 'Order was successfully destroyed.'
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_order
      @order = Order.find(params[:id])
    end

    # Only allow a trusted parameter "white list" through.
    def order_params
      params.require(:order).permit(:order_date, :user_id, :status)
    end
end

app/controllers/user_controller.rb
class UserController < ApplicationController
    def login
    session[:login] = 1
    session[:cart] = nil
    flash[:notice] = "Admin Login sucessfull!!"
    redirect_to :controller => :items
    end

    def logout
    session[:login] = nil
    session[:cart] = nil
    flash[:notice] = "You have been successfully logged out!!"
    redirect_to :controller => :items
    end

    def show
        @user = User.find(params[:id]   
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cart_helper.rb
module CartHelper
end

app/helpers/categories_helper.rb
module CategoriesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orderitems_helper.rb
module OrderitemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/user_helper.rb
module UserHelper
end

app/views/admins/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admins/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end %>
<% end %>

app/views/layouts/_categories.html.erb
<h1>Categories</h1>
<br>




 <% @categories.each do |category| %>
       <div class="itemhols">
           <p><%= category.title %></p>
           <%= link_to (image_tag category.image, :class=>"itemholsIm"), category %>
           <p><%= category.description %></p>
            
           <p><a href="/category/<%= category.title %>" class="button"><%= category.title %></a></p>
           
         </div>
    
    <% end %>

app/views/layouts/_footer.html.erb
<footer class="foot">
     <div id="footer1">
        <p>Ramen Store, <br>Unit 1, <br>Business Park,<br> Ramenstown, <br>Ireland</p>
        <p>T: 0082-RAMEN-STORE</p>
    </div>
    <div id="footer2">
        <p>©2021 Ramen Store. All rights reserved.</p>
    </div>
    <div id="footer3">
    <% if admin_signed_in? %>
        <%= link_to 'New Item', new_item_path, :class =>"button", :role=>"button" %>
        <%= link_to 'New Category', new_category_path, :class =>"button", :role=>"button" %>
    <% end %>
    </div>
</footer>

app/views/layouts/_header.html.erb
<header class="headSec">

 <h1>Ramen Store</h1>
 <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    
    <div class="container-fluid">
        <a class="navbar-brand" href="#">Menu</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
        <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
            <a class="nav-link active" aria-current="page" href="/">Home</a>
            </li>
            <li class="nav-item dropdown">
            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                Dropdown
            </a>
            <ul class="dropdown-menu" aria-labelledby="navbarDropdown">
                <li><a class="dropdown-item" href="#">Action</a></li>
                <li><a class="dropdown-item" href="#">Another action</a></li>
                <li><hr class="dropdown-divider"></li>
                <li><a class="dropdown-item" href="#">Something else here</a></li>
            </ul>
            </li>

            <li class="nav-item">
            <%= link_to "Items", items_path, class: "nav-link" %>
            </li>

            <li class="nav-item">
            <%= link_to "Categories", '/category', class: "nav-link" %>
            </li>


        <% if user_signed_in? %>
            <li class="nav-item">
            <%= link_to 'Edit Profile', edit_user_registration_path, class:"nav-link"%>
            </li>
            <li class="nav-item">
            <%= link_to 'Sign out', destroy_user_session_path, class:"nav-link", :method => :delete %>
            </li>   
            <li class="nav-item">
            <%= link_to "View Orders", orders_path, class:"nav-link" %></li>
            </li>
        <% else %>         
            <li class="nav-item">
            <%= link_to 'Register', new_user_registration_path, class:"nav-link" %>
            </li>
            <li class="nav-item">
            <%= link_to 'Sign in', new_user_session_path, class:"nav-link"%>
            </li>
        <% end %>   
        <li class="nav-item">
            <%= link_to "Cart", '/cart', class: "nav-link" %>
        </li>
        <li></li>
            <li class="nav-item">
            <%= link_to "About", about_path, class:"nav-link" %>
            </li>
            <li class="nav-item">
            <%= link_to "Contact Us", help_path, class:"nav-link" %>
            </li>
        <% if admin_signed_in? %>
            <li class="nav-item">
                <%= link_to 'Admin Sign out', destroy_admin_session_path, class:"nav-link", :method => :delete %>
            </li>
        <% else %>
            <li class="nav-item">
                <%= link_to 'Admin Sign in', new_admin_session_path, class:"nav-link"%>
            </li>
        <% end %>
            
        </ul>
        <form class="d-flex" action="/search">
            <input class="form-control me-2" name="q" type="search" placeholder="Search" aria-label="Search">
            <button class="btn btn-outline-success" type="submit">Search</button>
        </form>
        </div>
    </div>
    </nav>
        















        <% if false %>
 <ul>
    <li><%= link_to "Home", "/" %></li>
    <li><%= link_to "Items", items_path %></li>
    <li><%= link_to "About", about_path %></li>
    <li><%= link_to "Help", help_path %></li>
    <%# <li><%= link_to "Log In", login_path </li>%>
    <%# <li><%= link_to "Log Out", logout_path </li>%>
    <li><%= link_to "View Cart", "/cart" %></li>
    <li><%= link_to "View Orders", orders_path  %></li>
    <% if user_signed_in? %>
        <li><%= link_to 'Edit Profile', edit_user_registration_path %></li>
        <li><%= link_to 'Sign out', destroy_user_session_path, :method => :delete %></li>
    <% else %>
        <li><%= link_to 'Register', new_user_registration_path %></li>
        <li><%= link_to 'Sign in', new_user_session_path %></li>
    <% end %>

    <% if session[:login] == 1 %>
        <li><%= link_to "Admin Logout", logout_path %></li>
    <% else %>
        <li><%= link_to "Admin Login", login_path %></li>
    <% end %>
  
</ul>
<% end %>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>
 </header>

app/views/layouts/_search.html.erb
<%= form_tag("/search", :method => "post") do %>
<%= label_tag(:q, "Search for:") %>
<%= text_field_tag(:q) %>
<%= submit_tag("Search") %>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RamenStore <%= yield (:title) %></title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-giJF6kkoqNQ00vy+HMDP7azOuL0xtbfIcaT9wjKHr8RbDVddVHyTfAAsrekwKmP1" crossorigin="anonymous">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>

    <%= render 'layouts/header' %>
      <div class='container'>
        <div id='content'>
          <p class="notice"><%= flash[:notice] %></p>
            <%= yield %>
        </div>
        <div id='first-column'>
        </div>
        
      </div>
    <%= render 'layouts/footer' %>

    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.5.4/dist/umd/popper.min.js" integrity="sha384-q2kxQ16AaE6UbzuKqyBE9/u/KzioAlnx2maXQHiDX9d4/zp8Ok3f+M7DPm+Ib6IU" crossorigin="anonymous"></script>
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta1/dist/js/bootstrap.min.js" integrity="sha384-pQQkAEnwaBkjpqZ8RU1fF1AKtTcHJwFl3pblpTlHXybJjHpMYo79HY3hIi4NKxyj" crossorigin="anonymous"></script>



  </body>
  
</html>